---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-argocd-k3s-test-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Panzer1119/homelab-argocd-k3s-test-cluster.git
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      # Disable auto sync
      enabled: true
      # Removed deleted applications
      prune: true
      # So changes to child-apps (e.g. via the UI) do not trigger an auto sync
      selfHeal: false
...
