---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-connect
  namespace: 1password
spec:
  project: default
  source:
    chart: connect
    repoURL: https://1password.github.io/connect-helm-charts
    targetRevision: 2.1.1
    helm:
      values: |
        connect:
          create: true
          replicas: 1
        operator:
          create: true
          replicas: 1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 1password
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      allowEmpty: false
      selfHeal: true
...
