---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: democratic-csi-freenas-api-iscsi-config
  namespace: democratic-csi
spec:
  itemPath: "vaults/54l3mtxgy3y4ogx2wa5ral4dny/items/7atj25yrs45bqdktvpyzghzbzy"
...
