---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-freenas-api-iscsi-config
  namespace: democratic-csi
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: democratic-csi-freenas-api-iscsi-config
    template:
      engineVersion: v2
      data:
        "driver-config-file.yaml": |
          ---
          driver: "freenas-api-iscsi"
          instance_id:
          httpConnection:
            protocol: "{{ .http_connection_protocol }}"
            host: "{{ .http_connection_host }}"
            port: {{ .http_connection_port }}
            apiKey: "{{ .http_connection_api_key }}"
            allowInsecure: {{ .http_connection_allow_insecure }}
            # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
            # leave unset for auto-detection
            apiVersion: {{ .http_connection_api_version }}
          _private:
            csi:
              volume:
                idTemplate: "{{ `ns-{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}--pvc-{{ parameters.[csi.storage.k8s.io/pvc/name] }}` }}"
                deleteStrategy: "retain"
                idHash:
                  #strategy: "crc8"
                  #strategy: "crc16"
                  #strategy: "crc32"
                  strategy: "md5"
                  #strategy: "sha1"
          zfs:
            # can be used to set arbitrary values on the dataset/zvol
            # can use handlebars templates with the parameters from the storage class/CO
            datasetProperties:
              "democratic-csi:cluster-short-id": "{{ .cluster_short_id }}"
              "democratic-csi:csi.storage.k8s.io-pvc-namespace": "{{ `{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}` }}"
              "democratic-csi:csi.storage.k8s.io-pvc-name": "{{ `{{ parameters.[csi.storage.k8s.io/pvc/name] }}` }}"
            #  "org.freenas:description": "{{ `{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}` }}"
            #  "org.freenas:test": "{{ `{{ parameters.foo }}` }}"
            #  "org.freenas:test2": "some value"
            snapshotProperties:
              "democratic-csi:cluster-short-id": "{{ .cluster_short_id }}"
              "democratic-csi:csi.storage.k8s.io-pvc-namespace": "{{ `{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}` }}"
              "democratic-csi:csi.storage.k8s.io-pvc-name": "{{ `{{ parameters.[csi.storage.k8s.io/pvc/name] }}` }}"
            #  "org.freenas:key": "value"

            # total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
            # https://www.ixsystems.com/documentation/freenas/11.2-U5/storage.html#zfs-zvol-config-opts-tab
            # standard volume naming overhead is 46 chars
            # datasetParentName should therefore be 17 chars or less when using TrueNAS 12 or below (SCALE and 13+ do not have the same limits)
            # for work-arounds see https://github.com/democratic-csi/democratic-csi/issues/54
            datasetParentName: "{{ .zfs_global_dataset_parent_name }}/{{ .cluster_short_id }}/zvols"
            # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
            # they may be siblings, but neither should be nested in the other
            # do NOT comment this option out even if you don't plan to use snapshots, just leave it with dummy value
            detachedSnapshotsDatasetParentName: "{{ .zfs_global_dataset_parent_name }}/{{ .cluster_short_id }}/snaps"
            # "" (inherit), lz4, gzip-9, etc
            zvolCompression:
            # "" (inherit), on, off, verify
            zvolDedup:
            zvolEnableReservation: false
            # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
            zvolBlocksize:
          iscsi:
            targetPortal: "{{ .iscsi_target_portal }}"
            # for multipath
            targetPortals: [ ] # [ "server[:port]", "server[:port]", ... ]
            # leave empty to omit usage of -I with iscsiadm
            interface:

            # MUST ensure uniqueness
            # full iqn limit is 223 bytes, plan accordingly
            # default is "{{ `{{ name }}` }}"
            nameTemplate: "{{ `ns-{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}--pvc-{{ parameters.[csi.storage.k8s.io/pvc/name] }}` }}"
            namePrefix: "csi-{{ .cluster_short_id }}-"
            nameSuffix: ""

            # add as many as needed
            targetGroups:
              # get the correct ID from the "portal" section in the UI
              # https://github.com/democratic-csi/democratic-csi/issues/302
              # NOTE: the ID in the UI does NOT always match the ID in the DB, you must use the DB value
              - targetGroupPortalGroup: 1
                # get the correct ID from the "initiators" section in the UI
                targetGroupInitiatorGroup: 1
                # None, CHAP, or CHAP Mutual
                targetGroupAuthType: None
                # get the correct ID from the "Authorized Access" section of the UI
                # only required if using Chap
                targetGroupAuthGroup:

            extentCommentTemplate: "csi-{{ .cluster_short_id }}-{{ `{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}` }}"
            extentInsecureTpc: true
            extentXenCompat: false
            extentDisablePhysicalBlocksize: false
            # 512, 1024, 2048, or 4096,
            extentBlocksize: 4096
            # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
            extentRpm: "SSD"
            # 0-100 (0 == ignore)
            extentAvailThreshold: 0
          ...
  data:
    - secretKey: cluster_short_id
      remoteRef:
        key: "ujnkh23v5hdow6ohs7b72ytkce/Cluster-Short-ID"
    - secretKey: http_connection_protocol
      remoteRef:
        key: "ujnkh23v5hdow6ohs7b72ytkce/HTTP-Connection/Protocol"
    - secretKey: http_connection_host
      remoteRef:
        key: "ujnkh23v5hdow6ohs7b72ytkce/HTTP-Connection/Host"
    - secretKey: http_connection_port
      remoteRef:
        key: "ujnkh23v5hdow6ohs7b72ytkce/HTTP-Connection/Port"
    - secretKey: http_connection_api_key
      remoteRef:
        key: "ujnkh23v5hdow6ohs7b72ytkce/HTTP-Connection/API-Key"
    - secretKey: http_connection_allow_insecure
      remoteRef:
        key: "ujnkh23v5hdow6ohs7b72ytkce/HTTP-Connection/Allow-Insecure"
    - secretKey: http_connection_api_version
      remoteRef:
        key: "ujnkh23v5hdow6ohs7b72ytkce/HTTP-Connection/API-Version"
    - secretKey: zfs_global_dataset_parent_name
      remoteRef:
        key: "ujnkh23v5hdow6ohs7b72ytkce/ZFS/Global-Dataset-Parent-Name"
    - secretKey: iscsi_target_portal
      remoteRef:
        key: "ujnkh23v5hdow6ohs7b72ytkce/ISCSI/Target-Portal"
...
